[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/hh-salary"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
